name: StartOS Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies for building...
      run: sudo apt update && sudo apt install -y build-essential nasm xorriso qemu-system

    - name: Building with make...
      run: make

    - name: Running the build...
      run: qemu-system-x86_64 -cdrom StartOS.iso -m 64M -drive file=StartOS.vhd,if=ide,index=0 -boot d -smp 2 -serial stdio -display none
